name: 'Run tests against Firestore security rules'
on:
  push:

jobs:
  run-test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Maven test
        run: ./mvnw test